import org.junit.Test;
import java.util.*;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mwang27581' at '4/8/14 4:03 PM' with Gradle 1.11
 *
 * @author mwang27581, @date 4/8/14 4:03 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
		LinkedList mockedList = mock(LinkedList.class);
		when(mockedList.contains(argThat(isValid()))).thenReturn("element");
    }
}
