/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mwang27581' at '4/8/14 4:03 PM' with Gradle 1.11
 *
 * @author mwang27581, @date 4/8/14 4:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
