/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mwang27581' at '4/21/14 10:44 AM' with Gradle 1.11
 *
 * @author mwang27581, @date 4/21/14 10:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
